pipeline:
  name: python-ci-demo
  identifier: python_ci_demo
  projectIdentifier: PythonCIDemo
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: github_ci_demo_connector
        build: <+input>
  stages:
    - stage:
        name: Build_Test_Push
        identifier: Build_Test_Push
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install and Test
                  identifier: Install_Test
                  spec:
                    shell: Sh
                    command: |
                      python -m venv venv
                      . venv/bin/activate
                      pip install -U pip
                      pip install -r requirements.txt
                      pytest -q
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Docker Image
                  identifier: Build_Push
                  spec:
                    connectorRef: DockerTokenCI
                    repo: jcontin03/harness-ci-demo
                    tags:
                      - latest
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
