pipeline:
  name: python-ci-demo
  identifier: python_ci_demo
  orgIdentifier: default
  projectIdentifier: PythonCIDemo

  properties:
    ci:
      codebase:
        connectorRef: github_ci_demo_connector   # <- your Git connector
        build: <+input>                          # pick branch at run time

  stages:
    - stage:
        name: Build_Test_Push
        identifier: Build_Test_Push
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: Hosted
            spec:
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
          execution:
            steps:
              - step:
                  type: Run
                  name: Install & Test
                  identifier: Install_Test
                  spec:
                    shell: Sh
                    command: |
                      python -m venv venv
                      . venv/bin/activate
                      pip install -U pip
                      pip install -r requirements.txt
                      pytest -q

              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build & Push Docker Image
                  identifier: Build_Push
                  spec:
                    connectorRef: Docker-Token-CI            # <- your DockerHub connector
                    repo: jcontin03/harness-ci-demo          # <- DockerHub repo (user/repo)
                    dockerfile: Dockerfile
                    context: .
                    tags:
                      - latest
                      - <+pipeline.sequenceId>

          caching:
            enabled: true
            key: python-ci-demo-cache

        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
