pipeline:
  name: python-ci-demo
  identifier: python_ci_demo
  projectIdentifier: PythonCIDemo
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: github_ci_demo_connector
        build: <+input>
  stages:
    - stage:
        name: Build_Test_Push
        identifier: Build_Test_Push
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install and Test
                  identifier: Install_Test
                  spec:
                    shell: Sh
                    command: |
                      python -m venv venv
                      . venv/bin/activate
                      pip install -U pip
                      pip install -r requirements.txt
                      pytest -q
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Docker Image
                  identifier: Build_Push
                  spec:
                    connectorRef: DockerTokenCI
                    repo: lutherstark/harness-ci-demo
                    tags:
                      - latest
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
    - stage:
        name: Deploy_to_K8s
        identifier: Deploy_to_K8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: pythoncidemo
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: Retry
                    spec:
                      retryCount: 2
                      retryIntervals:
                        - 30s
                        - 1m
                      onRetryFailure:
                        action:
                          type: MarkAsFailure
          environment:
            environmentRef: demo
            deployToAll: false
            infrastructureDefinitions:
              - identifier: demo_infra
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: false
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
